name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker buildx build --file CRUD-App-Tasks-MongoDb-Flask/Dockerfile \
          --context ./CRUD-App-Tasks-MongoDb-Flask \
          --tag aleksandarstojanov/kiii-project-crud-app-docker:latest \
          --platform linux/amd64,linux/arm64 --push .

    - name: Log out from Docker Hub
      run: |
        docker logout
